pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh '''
          echo ">>> Compiling Java HelloWorld..."
          cat > HelloWorld.java <<EOF
          public class HelloWorld {
              public static void main(String[] args) {
                  System.out.println("Hello from Jenkins Pipeline with Docker!");
              }
          }
          EOF

          javac HelloWorld.java
          java HelloWorld
        '''
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:19-alpine' }
      }
      steps {
        sh '''
          echo ">>> Running Node.js Hello script..."
          echo "console.log('Hello from Jenkins Pipeline with Node.js!')" > hello.js
          node hello.js
        '''
      }
    }
  }
}
